id = "lovely"
name = "Lovely"
version = "0.1.0"
schema_version = 1
authors = ["Miciah Henderson <miciahjohnhenderson@gmail.com>"]
description = "Support for the Lovely programming language"
repository = "https://github.com/kiahjh/lovely-zed-extension"
